{
  nu = true;                # line numbers
  rnu = true;               # relative line numbers
  so = 5;                   # scrolloff
  stal = 1;                 # show tab line
  wildmenu = true;          # enable wildmenu
  ruler = true;             # show cursor position
  cmdheight = 0;            # minimal command bar
  hid = true;               # hidden buffers
  ignorecase = true;        # case-insensitive search
  smartcase = true;         # smart-case search
  hlsearch = true;          # highlight search matches
  incsearch = true;         # incremental search
  magic = true;             # use "magic" regex by default
  showmatch = true;         # highlight matching bracket
  splitright = true;        # vertical split to the right
  clipboard = "unnamedplus"; # system clipboard
  syntax = "on";            # enable syntax highlighting
  ai = true;                # auto indent
  si = true;                # smart indent
  wrap = true;              # line wrapping
  expandtab = true;         # spaces instead of tabs
  smarttab = true;          # smart tab behaviour
  sw = 4;                   # shiftwidth
  ts = 4;                   # tabstop
  lbr = true;               # linebreak for wrapping
  tw = 80;                  # textwidth
  backspace = "eol,start,indent"; # backspace behavior
  spelllang = "en_us,it";   # spell languages
  termguicolors = true;     # truecolor support
}
